# Generated by Django 5.0.1 on 2024-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_price_inr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
