# Generated by Django 5.0.1 on 2024-04-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_sale_price_inr_alter_product_price_inr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_inr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price_inr',
        ),
    ]
