# Generated by Django 5.0.1 on 2024-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_price_remove_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_inr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price_inr',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
