# Generated by Django 5.0.1 on 2024-04-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_price_remove_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_inr',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_price_inr',
            new_name='sale_price',
        ),
    ]
